sudo: required
services:
  - docker

before_install:
  - docker build -t charlottebai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true charlottebai/docker-react npm run test
#  - docker run charlottebai/docker-react npm run test -- --coverage